# 1. Redirigir todo el tráfico HTTP a HTTPS
server {
    listen 80;
    server_name regensaludpos.com www.regensaludpos.com;
    return 301 https://$host$request_uri;
}

# 2. Configuración de Servidor Seguro (HTTPS)
server {
    listen 443 ssl;
    server_name regensaludpos.com www.regensaludpos.com;

    # Rutas exactas que te dio Certbot
    ssl_certificate /etc/letsencrypt/live/regensaludpos.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/regensaludpos.com/privkey.pem;

    # Optimización de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Tu conexión con el Backend (Gateway)
    location /api/ {
        proxy_pass http://gateway-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}